name: database
version: 1.0.0


environment:
  sdk: ^3.2.3

dependencies:
  drift: ^2.15.0
  drift_postgres: ^1.2.0
  postgres: ^3.1.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
