POST http://localhost:8080/user
Content-Type: application/json

Fedor

###

GET http://localhost:8080/user

###

DELETE http://localhost:8080/user/1

###

GET http://localhost:8080/user/2

###

PATCH  http://localhost:8080/user/2?name=Fed