POST http://localhost:8080/user
Content-Type: application/json

Fedor

###

GET http://localhost:8080/user

###

DELETE http://localhost:8080/user/5

###

GET http://localhost:8080/user/5

###

PATCH  http://localhost:8080/user/5?name=Fed