name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shared:
    path: ../shared
  database:
    path: packages/database
  dart_frog: ^1.1.0

dev_dependencies:
  mocktail: 1.0.0
  test: ^1.19.2
  lints: ">=2.0.0 <4.0.0"
  shelf_router_generator: 1.1.0
  build_runner: 2.4.8
