targets:
  $default:
    builders:
      json_serializable:
        options: 
          checked: true
          explicit_to_json: true
      freezed:
        options: 
          when:
            when: false
            when_or_null: false
            maybe_when: false
          map:
            map: false
            map_or_null: false
            maybe_map: false