name: shared
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  database:
    path: ../server/packages/database

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0
