name: shared
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  database:
    path: ../server/packages/database
  grpc: ^3.2.4
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
